#!/bin/bash

echo "🔍 Database Connection Debug Script"
echo "==================================="

echo ""
echo "📋 Step 1: Check Environment Variables"
echo "Go to your Textbook_RAG_Assistant service → Variables tab"
echo "Make sure you have:"
echo "✅ SPRING_PROFILES_ACTIVE=cloud"
echo "✅ DATABASE_URL=postgresql://postgres:PASSWORD@postgres.railway.internal:5432/railway"
echo ""

echo "📋 Step 2: Check App Logs"
echo "Go to Textbook_RAG_Assistant → Logs"
echo "Look for these messages:"
echo "✅ 'Database connection test successful!'"
echo "❌ 'Falling back to H2 in-memory database'"
echo "❌ 'Database connection test failed'"
echo ""

echo "📋 Step 3: Test Database Connection"
echo "In Textbook_RAG_Assistant → Deployments → Console, run:"
echo "curl -v postgresql://postgres:PASSWORD@postgres.railway.internal:5432/railway"
echo ""

echo "📋 Step 4: Check Service Dependencies"
echo "Go to Textbook_RAG_Assistant → Settings"
echo "Look for 'Dependencies' or 'Connected Services'"
echo "Make sure PostgreSQL is listed as a dependency"
echo ""

echo "📋 Step 5: Force Redeploy"
echo "1. Go to Textbook_RAG_Assistant → Deployments"
echo "2. Click 'Redeploy' to force a fresh deployment"
echo "3. Watch the logs during deployment"
echo ""

echo "📋 Step 6: Alternative - Manual Table Creation"
echo "If nothing works, we can create tables manually:"
echo "1. Go to PostgreSQL service → Connect"
echo "2. Run these SQL commands:"
echo ""
echo "CREATE TABLE documents ("
echo "  id BIGSERIAL PRIMARY KEY,"
echo "  filename VARCHAR(255) NOT NULL,"
echo "  original_filename VARCHAR(255) NOT NULL,"
echo "  file_path VARCHAR(500) NOT NULL,"
echo "  file_size BIGINT NOT NULL,"
echo "  content_type VARCHAR(100) NOT NULL,"
echo "  extracted_text TEXT,"
echo "  uploaded_at TIMESTAMP NOT NULL,"
echo "  processed_at TIMESTAMP,"
echo "  status VARCHAR(20) NOT NULL,"
echo "  total_chunks INTEGER,"
echo "  error_message TEXT"
echo ");"
echo ""
echo "CREATE TABLE document_chunks ("
echo "  id BIGSERIAL PRIMARY KEY,"
echo "  document_id BIGINT NOT NULL,"
echo "  content TEXT NOT NULL,"
echo "  chunk_index INTEGER NOT NULL,"
echo "  embedding TEXT,"
echo "  created_at TIMESTAMP NOT NULL,"
echo "  metadata TEXT"
echo ");"
echo ""

echo "🎯 Most Likely Issues:"
echo "1. App is still using H2 fallback"
echo "2. Database URL is incorrect"
echo "3. Services aren't properly linked"
echo "4. Network connectivity issues"
echo ""

echo "📞 Next Steps:"
echo "1. Check the app logs first"
echo "2. Tell me what database connection messages you see"
echo "3. We'll fix the specific issue"
